global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nexus-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'redis-cache'
    static_configs:
      - targets: ['redis-cache:6379']

  - job_name: 'redis-queue'
    static_configs:
      - targets: ['redis-queue:6379']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
